' Developer Express Code Central Example:
' How to set different styles for even and odd rows in the DXGrid
' 
' The following example demonstrates how to mark odd and even rows in a grid with
' different background colors.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E981
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace OddEvenRows.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As OddEvenRows.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New OddEvenRows.Properties.Settings())), OddEvenRows.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return OddEvenRows.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
